;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014-06-10 2:53:11 PM

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=index.html	; 1.Introduction
IDH_1001=kmlmlkm.htm	; 2.Features
IDH_1005=Account.htm	; Account
IDH_1002=Create.htm	; Create
IDH_1003=Manage.htm	; Manage
IDH_1004=View.htm	; View
IDH_1010=menubar.htm	; 3. Menu Bar
IDH_1006=Contact.htm	; 4. Contact
