;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014-06-10 2:53:11 PM

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 1.Introduction index.html
#define IDH_1001	1001	; 2.Features kmlmlkm.htm
#define IDH_1005	1005	; Account Account.htm
#define IDH_1002	1002	; Create Create.htm
#define IDH_1003	1003	; Manage Manage.htm
#define IDH_1004	1004	; View View.htm
#define IDH_1010	1010	; 3. Menu Bar menubar.htm
#define IDH_1006	1006	; 4. Contact Contact.htm
